export { default as HeroSection } from './HeroSection'
export { default as ScrollStorySection } from './ScrollStorySection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as HotAssetsSection } from './HotAssetsSection'
export { default as TrustSection } from './TrustSection'
export { default as FooterCTASection } from './FooterCTASection'
